# action.yml
name: 'Action of authentication'
description: 'authentication and push images google artifact registry'
inputs:
  INPUT_GCLOUD_ACCOUNT:
    description: 'credentials for gcloud in base 64 format'
    required: true

outputs:
  repos:
    description: 'List of repositories'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_CREDENTIALS_IN_TEXT: ${{ inputs.INPUT_GCLOUD_ACCOUNT }}
